export default [
  { word: 'APPLE', hint: 'A red or green fruit.' },
  { word: 'OCEAN', hint: 'A vast body of saltwater.' },
  { word: 'CHAIR', hint: 'Something you sit on.' },
  { word: 'BREAD', hint: 'Used to make sandwiches.' },
  { word: 'CLOUD', hint: 'White and fluffy in the sky.' },
  { word: 'TRAIN', hint: 'Runs on tracks and carries people.' },
  { word: 'PAPER', hint: 'Used for writing or printing.' },
  { word: 'WATER', hint: 'Essential for life and often drunk.' },
  { word: 'STONE', hint: 'A small, hard natural object.' },
  { word: 'MUSIC', hint: 'Art made of sounds and rhythm.' },
  { word: 'GRASS', hint: 'Green and grows on the ground.' },
  { word: 'RIVER', hint: 'A large natural stream of water.' },
  { word: 'TABLE', hint: 'A flat surface for eating or working.' },
  { word: 'EARTH', hint: 'The planet we live on.' },
  { word: 'NIGHT', hint: 'When it is dark outside.' },
  { word: 'PLANT', hint: 'It grows and needs sunlight.' },
  { word: 'MOUSE', hint: 'A small animal or a computer device.' },
  { word: 'HOUSE', hint: 'A building where people live.' },
  { word: 'FLOWER', hint: 'A colorful part of a plant.' },
  { word: 'MIRROR', hint: 'Reflects your image.' },
  { word: 'GARDEN', hint: 'Used to grow plants or flowers.' },
  { word: 'PENCIL', hint: 'Used for writing or drawing.' },
  { word: 'BOTTLE', hint: 'Holds liquids like water.' },
  { word: 'SUNSET', hint: 'When the sun goes down.' },
  { word: 'SCHOOL', hint: 'Where children go to learn.' },
  { word: 'BRIDGE', hint: 'Allows crossing over water or roads.' },
  { word: 'WINDOW', hint: 'An opening in a wall with glass.' },
  { word: 'DESERT', hint: 'A dry, sandy area.' },
  { word: 'CANDLE', hint: 'Gives light when lit.' },
  { word: 'HELMET', hint: 'Protects your head.' },
  { word: 'PLANET', hint: 'Orbits a star like the Earth.' },
  { word: 'DOCTOR', hint: 'Treats sick people.' },
  { word: 'FOREST', hint: 'A large area full of trees.' },
  { word: 'MONKEY', hint: 'Climbs trees and eats bananas.' },
  { word: 'PUZZLE', hint: 'A game to test your mind.' },
  { word: 'ROCKET', hint: 'Used to travel into space.' },
  { word: 'GUITAR', hint: 'A musical instrument with strings.' },
  { word: 'CAMERA', hint: 'Used to take photos.' },
  { word: 'WALLET', hint: 'Holds cash and cards.' },
  { word: 'JUNGLE', hint: 'A dense forest in tropical regions.' },
  { word: 'PILLOW', hint: 'Rest your head on it while sleeping.' },
  { word: 'TROPHY', hint: 'Awarded for winning.' },
  { word: 'CASTLE', hint: 'A large building for kings and queens.' },
  { word: 'BASKET', hint: 'Used to carry items.' },
  { word: 'BUTTER', hint: 'A dairy product made from cream.' },
  { word: 'LEMON', hint: 'A sour yellow fruit.' },
  { word: 'BEACH', hint: 'A sandy area by the ocean.' },
  { word: 'BALLOON', hint: 'Inflatable and used for parties.' },
  { word: 'CLOCK', hint: 'Tells time.' },
  { word: 'EGG', hint: 'Laid by birds and eaten for breakfast.' },
  { word: 'FIRE', hint: 'Produces heat and light.' },
  { word: 'MOON', hint: "Earth's natural satellite." },
  { word: 'FROG', hint: 'A green animal that jumps.' },
  { word: 'BRUSH', hint: 'Used to paint or clean.' },
  { word: 'CAKE', hint: 'A sweet dessert often for birthdays.' },
  { word: 'STARS', hint: 'Twinkling lights in the night sky.' },
  { word: 'CUP', hint: 'Used to drink tea or coffee.' },
  { word: 'KEY', hint: 'Unlocks a door or starts a car.' },
  { word: 'DOOR', hint: 'Allows entry into a room or building.' },
  { word: 'BOOK', hint: 'A collection of written pages.' },
  { word: 'BAG', hint: 'Used to carry items.' },
  { word: 'FISH', hint: 'Lives in water and has gills.' },
  { word: 'RING', hint: 'A circular piece of jewelry.' },
  { word: 'LIGHT', hint: 'Opposite of dark.' },
  { word: 'COW', hint: 'A farm animal that gives milk.' },
  { word: 'MILK', hint: 'A white drink from cows.' },
  { word: 'DOG', hint: 'A loyal pet that barks.' },
  { word: 'CAT', hint: 'A pet that purrs.' },
  { word: 'TREE', hint: 'Grows tall with branches and leaves.' },
  { word: 'BOAT', hint: 'Floats on water.' },
  { word: 'BRICK', hint: 'Used to build walls.' },
  { word: 'TOY', hint: 'Children play with it.' },
  { word: 'SOAP', hint: 'Used to clean hands.' },
  { word: 'SHOES', hint: 'Worn on your feet.' },
  { word: 'RAIN', hint: 'Water falling from the sky.' },
  { word: 'CLOUD', hint: 'White and fluffy in the sky.' },
  { word: 'HAT', hint: 'Worn on the head for style or warmth.' },
  { word: 'CAR', hint: 'A vehicle with four wheels.' },
  { word: 'FORK', hint: 'Used to eat food.' },
  { word: 'KNIFE', hint: 'Used to cut food.' },
  { word: 'ROAD', hint: 'Used by cars for travel.' },
  { word: 'MAP', hint: 'Shows locations.' },
  { word: 'PEAR', hint: 'A green fruit shaped like a bell.' },
  { word: 'SUN', hint: 'The star that provides Earth with light.' },
  { word: 'HORSE', hint: 'An animal ridden for transportation or sport.' },
  { word: 'BRIDGE', hint: 'Connects two places over water.' },
  { word: 'FOOD', hint: 'What we eat to live.' },
  { word: 'BREAD', hint: 'Used for sandwiches.' },
  { word: 'CLOCK', hint: 'Tells time.' },
  { word: 'PLANE', hint: 'Flies in the sky for travel.' },
  { word: 'FENCE', hint: 'Surrounds a yard or garden.' },
  { word: 'GLASS', hint: 'Transparent and fragile.' },
  { word: 'WOOD', hint: 'Comes from trees.' },
  { word: 'SUGAR', hint: 'Sweet and used in desserts.' },
  { word: 'CANDY', hint: 'A sweet treat.' },
  { word: 'STICK', hint: 'A small, thin piece of wood.' },
  { word: 'BELL', hint: 'Rings to make a sound.' },
  { word: 'CHAIR', hint: 'Something you sit on.' },
  { word: 'SNAKE', hint: 'A slithering reptile.' },
  { word: 'LAMP', hint: 'Provides light indoors.' },
];
